name: "Build"
on:
  - push
  - pull_request

env:
  CMAKE_BUILD_TYPE: Debug

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "Ubuntu - Latest GCC",    os: ubuntu-latest,  cmake_c_compiler: "gcc" }
        - { name: "Ubuntu - Latest Clang",  os: ubuntu-latest,  cmake_c_compiler: "clang" }
        - { name: "MacOS - Latest Clang",   os: macos-latest,   cmake_c_compiler: "clang" }
        - { name: "Windows - Latest MSVC",  os: windows-latest, cmake_c_compiler: "msvc" }
    steps:
    - uses: actions/checkout@v3
    - name: "Install CMake"
      uses: lukka/get-cmake@latest
    - if: matrix.os == 'windows-latest' && matrix.config.cmake_c_compiler == 'msvc'
      name: "Install MSVC"
      uses: ilammy/msvc-dev-cmd@v1
    - if: matrix.os == 'ubuntu-latest' && matrix.cmake_c_compiler == 'gcc'
      name: "Install GCC"
      run: sudo apt update && sudo apt install -y build-essential gcc make
    - if: matrix.os == 'ubuntu-latest' && matrix.cmake_c_compiler == 'clang'
      name: "Install Clang"
      run: sudo apt update && sudo apt install -y build-essential clang make
    - name: "Configure"
      run: cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.config.cmake_c_compiler }}
    - name: "Build"
      run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
    - if: matrix.config.os == 'ubuntu-latest'
      name: "Install (Ubuntu)"
      run: sudo cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}
    - if: matrix.config.os != 'ubuntu-latest'
      name: "Install (Windows)"
      run: cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}
