name: "Unit tests"
on:
  push

jobs:
  unit_tests:
      runs-on: "ubuntu-latest"
      steps:
      - uses: "actions/checkout@v2"
      - name: "install build-essential, cmake and coverage tools"
        run: |
          sudo apt update
          sudo apt install -y cmake gcovr libghc-criterion-dev
      - name: "install criterion (unit testing library)"
        run: ${GITHUB_WORKSPACE}/.github/install_criterion.sh
        shell: bash
      - name: "build"
        run: |
          cd tests
          mkdir build
          cd build
          cmake ..
          make
      - name: "run tests"
        run: |
          ./tests/build/unit_tests
      - name: "generate coverage report"
        run: |
          gcovr -f '' -r . --exclude=tests/ --xml -o coverage.xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '25 80'
